# Generated by Django 3.0.2 on 2020-01-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_logistics', '0003_auto_20200120_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
