# Generated by Django 3.0.2 on 2020-01-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_logistics', '0004_auto_20200120_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'placed'), (1, 'in processing'), (2, 'prepared for delivery'), (3, 'in delivery'), (4, 'delivered')]),
        ),
    ]
