# Generated by Django 3.0.1 on 2019-12-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
