# Generated by Django 3.0.2 on 2020-01-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_cover',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.DeleteModel(
            name='BookCover',
        ),
    ]
